name: arcane_jaspr
description: "A Jaspr web framework port of the Arcane UI component library. Build beautiful web applications with Dart using familiar Arcane patterns."
version: 2.4.0
homepage: https://arcane.art
documentation: https://arcanearts.github.io/
repository: https://github.com/ArcaneArts/arcane_jaspr

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  jaspr: ^0.22.0
  meta: ^1.17.0
  fast_log: ^1.0.7
  web: ^1.1.1
  http: ^1.6.0

dev_dependencies:
  jaspr_test: ^0.22.0
  lints: ^6.0.0
  build_runner: ^2.10.4
  jaspr_builder: ^0.22.0



scripts:
  # dart autoconst
  autoconst: dart-auto-const
  # Code Generation
  build_runner: dart run build_runner build --delete-conflicting-outputs